[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --noinput && gunicorn portfolio.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
healthcheckPath = "/"
restartPolicyType = "on_failure"
